import Header from "../components/ui/admin/Header";
import Sidebar from "../components/ui/admin/Sidebar";

export const metadata = {
    title: "پنل کاربری",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex min-h-screen">
      <div className="w-1/6 bg-[var(--sidebar-bg)] text-[var(--text-color)] p-4">
        <Sidebar />
      </div>
      <div className="w-5/6">
        <Header />
        <main className="content">{children}</main>
      </div>
    </div>
  );
}
