import "./../styles/globals.css";
import localFont from "next/font/local";
import Sidebar from "@/app/components/ui/admin/Sidebar";
import Header from "@/app/components/ui/admin/Header";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirmatn = localFont({
  src: [
    {
      path: "./../fonts/webfonts/Vazirmatn-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../fonts/webfonts/Vazirmatn-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],

  variable: "--font-vazirmatn",
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={vazirmatn.variable}>
      <head>
        <link
          rel="stylesheet"
          href="/font-awesome-4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body>
      <div className="flex min-h-screen">
        <div className="w-1/6 bg-[var(--sidebar-bg)] text-[var(--text-color)] p-4">
          <Sidebar />
        </div>

        <div className="w-5/6 p-4">
          <Header />
          <main className="content">
            {children}
          </main>
        </div>
      </div>
      </body>
    </html>
  );
}
